name: 'Setup Java and Gradle'
description: 'Sets up JDK 25 and Gradle with caching'
runs:
  using: "composite"
  steps:
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'corretto'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Grant Permissions to gradlew
      shell: bash
      working-directory: ./be
      run: chmod +x gradlew
