services:
  db:
    image: postgres:16.8
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_user=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
