### Get all caps
GET {{baseUrl}}/caps
Accept: application/json

### Get caps by country
GET {{baseUrl}}/caps?country=BE
Accept: application/json

### Get cap by ID
GET {{baseUrl}}/caps/cap-123
Accept: application/json

### Create cap
POST {{baseUrl}}/caps
Content-Type: application/json

{
  "name": "Sample Cap",
  "description": "A sample cap description",
  "amount": 5,
  "country": "BE"
}

### Update cap
PUT {{baseUrl}}/caps/cap-123
Content-Type: application/json

{
  "name": "Updated Cap",
  "description": "An updated cap description",
  "amount": 10,
  "country": "BE"
}

### Delete cap by ID
DELETE {{baseUrl}}/caps/cap-123
